### Work with txt_read and read_table

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly
import plotly.express as px

countries_data = pd.read_csv('data/countries.csv', sep=';') 
countries_data.to_csv('data/countries.txt',sep=' ',index=False)

tx_df = pd.read_table('data/countries.txt',sep=' ',index_col=['country'])
display(tx_df)

           population    square
country
Англия          56.29    133396
Канада          38.05   9984670
США            322.28   9826630
Россия         146.24  17125191
Украина         45.50    603628
Беларусь         9.50    207600
Казахстан       17.04   2724902

### Applying the header parameter

In [3]:
melb_data = pd.read_csv('data/melb_data_ps.csv',header=None)

display(melb_data.head(3))

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
1,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1,202.0,126.0,1970,Yarra,-37.7996,144.9984,Northern Metropolitan,4019,"-37.7996, 144.9984"
2,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0,156.0,79.0,1900,Yarra,-37.8079,144.9934,Northern Metropolitan,4019,"-37.8079, 144.9934"

### Problems with encoding of the source data

In [4]:
# Считываем данные из файла с неизвестной кодировкой в переменную, создавая объект DataFrame
data = pd.read_csv('data/ErrorEnCoding.csv', header=None)
display(data)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 33: invalid continuation byte